[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/pdf"
  to = "/pdf.html"
  status = 200

# Route API requests to Netlify Function
[[redirects]]
  from = "/api/pdf"
  to = "/.netlify/functions/pdf"
  status = 200
  force = true

[[headers]]
  for = "/js/*"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"