[build]
  command = ""
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.15.0"
  CI = "false"

[functions."pdf"]
  timeout = 30 # Increase timeout to 30 seconds for PDF generation
